project_id = "ikwthbqubpwerygwbwzn"

[functions.test-elasticsearch]
verify_jwt = false

[functions.fetch-elastic-products]
verify_jwt = false

[functions.analyze-study-ai]
verify_jwt = false

[functions.dashboard-ai-chat]
verify_jwt = false

[functions.sync-patents-data]
verify_jwt = false

[functions.search-google-patents]
verify_jwt = false

[functions.get-patent-details]
verify_jwt = false

[functions.data-scheduler]
verify_jwt = false

[functions.ai-chat-quick]
verify_jwt = false

[functions.confirm-email]
verify_jwt = false

[functions.search-patents-bigquery]
verify_jwt = false

[functions.fetch-elasticsearch-data]
verify_jwt = false

[functions.generate-smart-alerts]
verify_jwt = false

[functions.get-data-correlations]
verify_jwt = false

[functions.generate-market-insights]
verify_jwt = false

[functions.list-elastic-products]
verify_jwt = false

[functions.search-capes-studies]
verify_jwt = false

