project_id = "ikwthbqubpwerygwbwzn"

[functions.dashboard-ai-chat]
verify_jwt = false

[functions.sync-agrofit-data]
verify_jwt = false

[functions.sync-patents-data]
verify_jwt = false

[functions.search-google-patents]
verify_jwt = false

[functions.get-patent-details]
verify_jwt = false

[functions.data-scheduler]
verify_jwt = false

[functions.ai-chat-quick]
verify_jwt = false

[functions.confirm-email]
verify_jwt = false

[functions.search-patents-bigquery]
[functions.insights-ai]
verify_jwt = false
